//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Banco", "FK_cidades_estados", "tb_estados", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DAL.tb_estados), "tb_cidades", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAL.tb_cidades), true)]
[assembly: EdmRelationshipAttribute("Banco", "FK_cliente_cidade", "tb_cidades", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAL.tb_cidades), "tb_clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAL.tb_clientes), true)]
[assembly: EdmRelationshipAttribute("Banco", "fk_solicitacoes_clientes", "tb_clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAL.tb_clientes), "tb_solicitacoes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAL.tb_solicitacoes), true)]
[assembly: EdmRelationshipAttribute("Banco", "fk_solicitacoes_status", "tb_status", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAL.tb_status), "tb_solicitacoes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAL.tb_solicitacoes), true)]
[assembly: EdmRelationshipAttribute("Banco", "fk_solicitacoes_usuario_cadastro", "tb_usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAL.tb_usuarios), "tb_solicitacoes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAL.tb_solicitacoes), true)]
[assembly: EdmRelationshipAttribute("Banco", "FK_solicitacoes_tipos", "tb_tipos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAL.tb_tipos), "tb_solicitacoes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAL.tb_solicitacoes), true)]
[assembly: EdmRelationshipAttribute("Banco", "fk_LogSolicitacoes_solicitacoes", "tb_solicitacoes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAL.tb_solicitacoes), "tb_LogSolicitacoes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAL.tb_LogSolicitacoes), true)]
[assembly: EdmRelationshipAttribute("Banco", "fk_LogSolicitacoes_usuarios", "tb_usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DAL.tb_usuarios), "tb_LogSolicitacoes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAL.tb_LogSolicitacoes), true)]
[assembly: EdmRelationshipAttribute("Banco", "FK_LogSolicitacoes_status", "tb_status", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DAL.tb_status), "tb_LogSolicitacoes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAL.tb_LogSolicitacoes), true)]

#endregion

namespace DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DBHelpX : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BaseDados object using the connection string found in the 'BaseDados' section of the application configuration file.
        /// </summary>
        public DBHelpX() : base("name=DBHelpX", "DBHelpX")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BaseDados object.
        /// </summary>
        public DBHelpX(string connectionString) : base(connectionString, "DBHelpX")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BaseDados object.
        /// </summary>
        public DBHelpX(EntityConnection connection) : base(connection, "DBHelpX")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_cidades> tb_cidades
        {
            get
            {
                if ((_tb_cidades == null))
                {
                    _tb_cidades = base.CreateObjectSet<tb_cidades>("tb_cidades");
                }
                return _tb_cidades;
            }
        }
        private ObjectSet<tb_cidades> _tb_cidades;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_clientes> tb_clientes
        {
            get
            {
                if ((_tb_clientes == null))
                {
                    _tb_clientes = base.CreateObjectSet<tb_clientes>("tb_clientes");
                }
                return _tb_clientes;
            }
        }
        private ObjectSet<tb_clientes> _tb_clientes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_estados> tb_estados
        {
            get
            {
                if ((_tb_estados == null))
                {
                    _tb_estados = base.CreateObjectSet<tb_estados>("tb_estados");
                }
                return _tb_estados;
            }
        }
        private ObjectSet<tb_estados> _tb_estados;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_solicitacoes> tb_solicitacoes
        {
            get
            {
                if ((_tb_solicitacoes == null))
                {
                    _tb_solicitacoes = base.CreateObjectSet<tb_solicitacoes>("tb_solicitacoes");
                }
                return _tb_solicitacoes;
            }
        }
        private ObjectSet<tb_solicitacoes> _tb_solicitacoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_status> tb_status
        {
            get
            {
                if ((_tb_status == null))
                {
                    _tb_status = base.CreateObjectSet<tb_status>("tb_status");
                }
                return _tb_status;
            }
        }
        private ObjectSet<tb_status> _tb_status;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_tipos> tb_tipos
        {
            get
            {
                if ((_tb_tipos == null))
                {
                    _tb_tipos = base.CreateObjectSet<tb_tipos>("tb_tipos");
                }
                return _tb_tipos;
            }
        }
        private ObjectSet<tb_tipos> _tb_tipos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_usuarios> tb_usuarios
        {
            get
            {
                if ((_tb_usuarios == null))
                {
                    _tb_usuarios = base.CreateObjectSet<tb_usuarios>("tb_usuarios");
                }
                return _tb_usuarios;
            }
        }
        private ObjectSet<tb_usuarios> _tb_usuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_LogSolicitacoes> tb_LogSolicitacoes
        {
            get
            {
                if ((_tb_LogSolicitacoes == null))
                {
                    _tb_LogSolicitacoes = base.CreateObjectSet<tb_LogSolicitacoes>("tb_LogSolicitacoes");
                }
                return _tb_LogSolicitacoes;
            }
        }
        private ObjectSet<tb_LogSolicitacoes> _tb_LogSolicitacoes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_cidades EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_cidades(tb_cidades tb_cidades)
        {
            base.AddObject("tb_cidades", tb_cidades);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_clientes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_clientes(tb_clientes tb_clientes)
        {
            base.AddObject("tb_clientes", tb_clientes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_estados EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_estados(tb_estados tb_estados)
        {
            base.AddObject("tb_estados", tb_estados);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_solicitacoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_solicitacoes(tb_solicitacoes tb_solicitacoes)
        {
            base.AddObject("tb_solicitacoes", tb_solicitacoes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_status EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_status(tb_status tb_status)
        {
            base.AddObject("tb_status", tb_status);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_tipos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_tipos(tb_tipos tb_tipos)
        {
            base.AddObject("tb_tipos", tb_tipos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_usuarios(tb_usuarios tb_usuarios)
        {
            base.AddObject("tb_usuarios", tb_usuarios);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_LogSolicitacoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_LogSolicitacoes(tb_LogSolicitacoes tb_LogSolicitacoes)
        {
            base.AddObject("tb_LogSolicitacoes", tb_LogSolicitacoes);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Banco", Name="tb_cidades")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_cidades : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_cidades object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tb_cidades Createtb_cidades(global::System.Int32 id)
        {
            tb_cidades tb_cidades = new tb_cidades();
            tb_cidades.id = id;
            return tb_cidades;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> estado_id
        {
            get
            {
                return _estado_id;
            }
            set
            {
                Onestado_idChanging(value);
                ReportPropertyChanging("estado_id");
                _estado_id = StructuralObject.SetValidValue(value, "estado_id");
                ReportPropertyChanged("estado_id");
                Onestado_idChanged();
            }
        }
        private Nullable<global::System.Int32> _estado_id;
        partial void Onestado_idChanging(Nullable<global::System.Int32> value);
        partial void Onestado_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String uf
        {
            get
            {
                return _uf;
            }
            set
            {
                OnufChanging(value);
                ReportPropertyChanging("uf");
                _uf = StructuralObject.SetValidValue(value, true, "uf");
                ReportPropertyChanged("uf");
                OnufChanged();
            }
        }
        private global::System.String _uf;
        partial void OnufChanging(global::System.String value);
        partial void OnufChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, true, "nome");
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Banco", "FK_cidades_estados", "tb_estados")]
        public tb_estados tb_estados
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_estados>("Banco.FK_cidades_estados", "tb_estados").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_estados>("Banco.FK_cidades_estados", "tb_estados").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_estados> tb_estadosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_estados>("Banco.FK_cidades_estados", "tb_estados");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_estados>("Banco.FK_cidades_estados", "tb_estados", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Banco", "FK_cliente_cidade", "tb_clientes")]
        public EntityCollection<tb_clientes> tb_clientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_clientes>("Banco.FK_cliente_cidade", "tb_clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_clientes>("Banco.FK_cliente_cidade", "tb_clientes", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Banco", Name="tb_clientes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_clientes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_clientes object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="status">Initial value of the status property.</param>
        /// <param name="cidade_id">Initial value of the cidade_id property.</param>
        public static tb_clientes Createtb_clientes(global::System.Int32 id, global::System.Boolean status, global::System.Int32 cidade_id)
        {
            tb_clientes tb_clientes = new tb_clientes();
            tb_clientes.id = id;
            tb_clientes.status = status;
            tb_clientes.cidade_id = cidade_id;
            return tb_clientes;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cpf_cnpj
        {
            get
            {
                return _cpf_cnpj;
            }
            set
            {
                Oncpf_cnpjChanging(value);
                ReportPropertyChanging("cpf_cnpj");
                _cpf_cnpj = StructuralObject.SetValidValue(value, true, "cpf_cnpj");
                ReportPropertyChanged("cpf_cnpj");
                Oncpf_cnpjChanged();
            }
        }
        private global::System.String _cpf_cnpj;
        partial void Oncpf_cnpjChanging(global::System.String value);
        partial void Oncpf_cnpjChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rg
        {
            get
            {
                return _rg;
            }
            set
            {
                OnrgChanging(value);
                ReportPropertyChanging("rg");
                _rg = StructuralObject.SetValidValue(value, true, "rg");
                ReportPropertyChanged("rg");
                OnrgChanged();
            }
        }
        private global::System.String _rg;
        partial void OnrgChanging(global::System.String value);
        partial void OnrgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, true, "nome");
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nome_fantasia
        {
            get
            {
                return _nome_fantasia;
            }
            set
            {
                Onnome_fantasiaChanging(value);
                ReportPropertyChanging("nome_fantasia");
                _nome_fantasia = StructuralObject.SetValidValue(value, true, "nome_fantasia");
                ReportPropertyChanged("nome_fantasia");
                Onnome_fantasiaChanged();
            }
        }
        private global::System.String _nome_fantasia;
        partial void Onnome_fantasiaChanging(global::System.String value);
        partial void Onnome_fantasiaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String razao_social
        {
            get
            {
                return _razao_social;
            }
            set
            {
                Onrazao_socialChanging(value);
                ReportPropertyChanging("razao_social");
                _razao_social = StructuralObject.SetValidValue(value, true, "razao_social");
                ReportPropertyChanged("razao_social");
                Onrazao_socialChanged();
            }
        }
        private global::System.String _razao_social;
        partial void Onrazao_socialChanging(global::System.String value);
        partial void Onrazao_socialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telefone
        {
            get
            {
                return _telefone;
            }
            set
            {
                OntelefoneChanging(value);
                ReportPropertyChanging("telefone");
                _telefone = StructuralObject.SetValidValue(value, true, "telefone");
                ReportPropertyChanged("telefone");
                OntelefoneChanged();
            }
        }
        private global::System.String _telefone;
        partial void OntelefoneChanging(global::System.String value);
        partial void OntelefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String celular
        {
            get
            {
                return _celular;
            }
            set
            {
                OncelularChanging(value);
                ReportPropertyChanging("celular");
                _celular = StructuralObject.SetValidValue(value, true, "celular");
                ReportPropertyChanged("celular");
                OncelularChanged();
            }
        }
        private global::System.String _celular;
        partial void OncelularChanging(global::System.String value);
        partial void OncelularChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rua
        {
            get
            {
                return _rua;
            }
            set
            {
                OnruaChanging(value);
                ReportPropertyChanging("rua");
                _rua = StructuralObject.SetValidValue(value, true, "rua");
                ReportPropertyChanged("rua");
                OnruaChanged();
            }
        }
        private global::System.String _rua;
        partial void OnruaChanging(global::System.String value);
        partial void OnruaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> numero
        {
            get
            {
                return _numero;
            }
            set
            {
                OnnumeroChanging(value);
                ReportPropertyChanging("numero");
                _numero = StructuralObject.SetValidValue(value, "numero");
                ReportPropertyChanged("numero");
                OnnumeroChanged();
            }
        }
        private Nullable<global::System.Int32> _numero;
        partial void OnnumeroChanging(Nullable<global::System.Int32> value);
        partial void OnnumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String complemente
        {
            get
            {
                return _complemente;
            }
            set
            {
                OncomplementeChanging(value);
                ReportPropertyChanging("complemente");
                _complemente = StructuralObject.SetValidValue(value, true, "complemente");
                ReportPropertyChanged("complemente");
                OncomplementeChanged();
            }
        }
        private global::System.String _complemente;
        partial void OncomplementeChanging(global::System.String value);
        partial void OncomplementeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bairro
        {
            get
            {
                return _bairro;
            }
            set
            {
                OnbairroChanging(value);
                ReportPropertyChanging("bairro");
                _bairro = StructuralObject.SetValidValue(value, true, "bairro");
                ReportPropertyChanged("bairro");
                OnbairroChanged();
            }
        }
        private global::System.String _bairro;
        partial void OnbairroChanging(global::System.String value);
        partial void OnbairroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cep
        {
            get
            {
                return _cep;
            }
            set
            {
                OncepChanging(value);
                ReportPropertyChanging("cep");
                _cep = StructuralObject.SetValidValue(value, true, "cep");
                ReportPropertyChanged("cep");
                OncepChanged();
            }
        }
        private global::System.String _cep;
        partial void OncepChanging(global::System.String value);
        partial void OncepChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, "status");
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.Boolean _status;
        partial void OnstatusChanging(global::System.Boolean value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cidade_id
        {
            get
            {
                return _cidade_id;
            }
            set
            {
                Oncidade_idChanging(value);
                ReportPropertyChanging("cidade_id");
                _cidade_id = StructuralObject.SetValidValue(value, "cidade_id");
                ReportPropertyChanged("cidade_id");
                Oncidade_idChanged();
            }
        }
        private global::System.Int32 _cidade_id;
        partial void Oncidade_idChanging(global::System.Int32 value);
        partial void Oncidade_idChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Banco", "FK_cliente_cidade", "tb_cidades")]
        public tb_cidades tb_cidades
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_cidades>("Banco.FK_cliente_cidade", "tb_cidades").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_cidades>("Banco.FK_cliente_cidade", "tb_cidades").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_cidades> tb_cidadesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_cidades>("Banco.FK_cliente_cidade", "tb_cidades");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_cidades>("Banco.FK_cliente_cidade", "tb_cidades", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Banco", "fk_solicitacoes_clientes", "tb_solicitacoes")]
        public EntityCollection<tb_solicitacoes> tb_solicitacoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_solicitacoes>("Banco.fk_solicitacoes_clientes", "tb_solicitacoes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_solicitacoes>("Banco.fk_solicitacoes_clientes", "tb_solicitacoes", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Banco", Name="tb_estados")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_estados : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_estados object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="uf">Initial value of the uf property.</param>
        /// <param name="nome">Initial value of the nome property.</param>
        public static tb_estados Createtb_estados(global::System.Int32 id, global::System.String uf, global::System.String nome)
        {
            tb_estados tb_estados = new tb_estados();
            tb_estados.id = id;
            tb_estados.uf = uf;
            tb_estados.nome = nome;
            return tb_estados;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String uf
        {
            get
            {
                return _uf;
            }
            set
            {
                OnufChanging(value);
                ReportPropertyChanging("uf");
                _uf = StructuralObject.SetValidValue(value, false, "uf");
                ReportPropertyChanged("uf");
                OnufChanged();
            }
        }
        private global::System.String _uf;
        partial void OnufChanging(global::System.String value);
        partial void OnufChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, false, "nome");
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Banco", "FK_cidades_estados", "tb_cidades")]
        public EntityCollection<tb_cidades> tb_cidades
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_cidades>("Banco.FK_cidades_estados", "tb_cidades");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_cidades>("Banco.FK_cidades_estados", "tb_cidades", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Banco", Name="tb_LogSolicitacoes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_LogSolicitacoes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_LogSolicitacoes object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="solicitacoes_id">Initial value of the solicitacoes_id property.</param>
        public static tb_LogSolicitacoes Createtb_LogSolicitacoes(global::System.Int32 id, global::System.Int32 solicitacoes_id)
        {
            tb_LogSolicitacoes tb_LogSolicitacoes = new tb_LogSolicitacoes();
            tb_LogSolicitacoes.id = id;
            tb_LogSolicitacoes.solicitacoes_id = solicitacoes_id;
            return tb_LogSolicitacoes;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> data_registro
        {
            get
            {
                return _data_registro;
            }
            set
            {
                Ondata_registroChanging(value);
                ReportPropertyChanging("data_registro");
                _data_registro = StructuralObject.SetValidValue(value, "data_registro");
                ReportPropertyChanged("data_registro");
                Ondata_registroChanged();
            }
        }
        private Nullable<global::System.DateTime> _data_registro;
        partial void Ondata_registroChanging(Nullable<global::System.DateTime> value);
        partial void Ondata_registroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 solicitacoes_id
        {
            get
            {
                return _solicitacoes_id;
            }
            set
            {
                Onsolicitacoes_idChanging(value);
                ReportPropertyChanging("solicitacoes_id");
                _solicitacoes_id = StructuralObject.SetValidValue(value, "solicitacoes_id");
                ReportPropertyChanged("solicitacoes_id");
                Onsolicitacoes_idChanged();
            }
        }
        private global::System.Int32 _solicitacoes_id;
        partial void Onsolicitacoes_idChanging(global::System.Int32 value);
        partial void Onsolicitacoes_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String detalhamento
        {
            get
            {
                return _detalhamento;
            }
            set
            {
                OndetalhamentoChanging(value);
                ReportPropertyChanging("detalhamento");
                _detalhamento = StructuralObject.SetValidValue(value, true, "detalhamento");
                ReportPropertyChanged("detalhamento");
                OndetalhamentoChanged();
            }
        }
        private global::System.String _detalhamento;
        partial void OndetalhamentoChanging(global::System.String value);
        partial void OndetalhamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> usuario_cadastro_id
        {
            get
            {
                return _usuario_cadastro_id;
            }
            set
            {
                Onusuario_cadastro_idChanging(value);
                ReportPropertyChanging("usuario_cadastro_id");
                _usuario_cadastro_id = StructuralObject.SetValidValue(value, "usuario_cadastro_id");
                ReportPropertyChanged("usuario_cadastro_id");
                Onusuario_cadastro_idChanged();
            }
        }
        private Nullable<global::System.Int32> _usuario_cadastro_id;
        partial void Onusuario_cadastro_idChanging(Nullable<global::System.Int32> value);
        partial void Onusuario_cadastro_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> status_id
        {
            get
            {
                return _status_id;
            }
            set
            {
                Onstatus_idChanging(value);
                ReportPropertyChanging("status_id");
                _status_id = StructuralObject.SetValidValue(value, "status_id");
                ReportPropertyChanged("status_id");
                Onstatus_idChanged();
            }
        }
        private Nullable<global::System.Int32> _status_id;
        partial void Onstatus_idChanging(Nullable<global::System.Int32> value);
        partial void Onstatus_idChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Banco", "fk_LogSolicitacoes_solicitacoes", "tb_solicitacoes")]
        public tb_solicitacoes tb_solicitacoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_solicitacoes>("Banco.fk_LogSolicitacoes_solicitacoes", "tb_solicitacoes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_solicitacoes>("Banco.fk_LogSolicitacoes_solicitacoes", "tb_solicitacoes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_solicitacoes> tb_solicitacoesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_solicitacoes>("Banco.fk_LogSolicitacoes_solicitacoes", "tb_solicitacoes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_solicitacoes>("Banco.fk_LogSolicitacoes_solicitacoes", "tb_solicitacoes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Banco", "fk_LogSolicitacoes_usuarios", "tb_usuarios")]
        public tb_usuarios tb_usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuarios>("Banco.fk_LogSolicitacoes_usuarios", "tb_usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuarios>("Banco.fk_LogSolicitacoes_usuarios", "tb_usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_usuarios> tb_usuariosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuarios>("Banco.fk_LogSolicitacoes_usuarios", "tb_usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_usuarios>("Banco.fk_LogSolicitacoes_usuarios", "tb_usuarios", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Banco", "FK_LogSolicitacoes_status", "tb_status")]
        public tb_status tb_status
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_status>("Banco.FK_LogSolicitacoes_status", "tb_status").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_status>("Banco.FK_LogSolicitacoes_status", "tb_status").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_status> tb_statusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_status>("Banco.FK_LogSolicitacoes_status", "tb_status");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_status>("Banco.FK_LogSolicitacoes_status", "tb_status", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Banco", Name="tb_solicitacoes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_solicitacoes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_solicitacoes object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="tipo_id">Initial value of the tipo_id property.</param>
        /// <param name="status_id">Initial value of the status_id property.</param>
        /// <param name="usuario_cadastro_id">Initial value of the usuario_cadastro_id property.</param>
        /// <param name="clientes_id">Initial value of the clientes_id property.</param>
        public static tb_solicitacoes Createtb_solicitacoes(global::System.Int32 id, global::System.Int32 tipo_id, global::System.Int32 status_id, global::System.Int32 usuario_cadastro_id, global::System.Int32 clientes_id)
        {
            tb_solicitacoes tb_solicitacoes = new tb_solicitacoes();
            tb_solicitacoes.id = id;
            tb_solicitacoes.tipo_id = tipo_id;
            tb_solicitacoes.status_id = status_id;
            tb_solicitacoes.usuario_cadastro_id = usuario_cadastro_id;
            tb_solicitacoes.clientes_id = clientes_id;
            return tb_solicitacoes;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                OncodigoChanging(value);
                ReportPropertyChanging("codigo");
                _codigo = StructuralObject.SetValidValue(value, true, "codigo");
                ReportPropertyChanged("codigo");
                OncodigoChanged();
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tipo_id
        {
            get
            {
                return _tipo_id;
            }
            set
            {
                Ontipo_idChanging(value);
                ReportPropertyChanging("tipo_id");
                _tipo_id = StructuralObject.SetValidValue(value, "tipo_id");
                ReportPropertyChanged("tipo_id");
                Ontipo_idChanged();
            }
        }
        private global::System.Int32 _tipo_id;
        partial void Ontipo_idChanging(global::System.Int32 value);
        partial void Ontipo_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String solicitante
        {
            get
            {
                return _solicitante;
            }
            set
            {
                OnsolicitanteChanging(value);
                ReportPropertyChanging("solicitante");
                _solicitante = StructuralObject.SetValidValue(value, true, "solicitante");
                ReportPropertyChanged("solicitante");
                OnsolicitanteChanged();
            }
        }
        private global::System.String _solicitante;
        partial void OnsolicitanteChanging(global::System.String value);
        partial void OnsolicitanteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telefone
        {
            get
            {
                return _telefone;
            }
            set
            {
                OntelefoneChanging(value);
                ReportPropertyChanging("telefone");
                _telefone = StructuralObject.SetValidValue(value, true, "telefone");
                ReportPropertyChanged("telefone");
                OntelefoneChanged();
            }
        }
        private global::System.String _telefone;
        partial void OntelefoneChanging(global::System.String value);
        partial void OntelefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                OndescricaoChanging(value);
                ReportPropertyChanging("descricao");
                _descricao = StructuralObject.SetValidValue(value, true, "descricao");
                ReportPropertyChanged("descricao");
                OndescricaoChanged();
            }
        }
        private global::System.String _descricao;
        partial void OndescricaoChanging(global::System.String value);
        partial void OndescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String detalhamento
        {
            get
            {
                return _detalhamento;
            }
            set
            {
                OndetalhamentoChanging(value);
                ReportPropertyChanging("detalhamento");
                _detalhamento = StructuralObject.SetValidValue(value, true, "detalhamento");
                ReportPropertyChanged("detalhamento");
                OndetalhamentoChanged();
            }
        }
        private global::System.String _detalhamento;
        partial void OndetalhamentoChanging(global::System.String value);
        partial void OndetalhamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> data_cadastro
        {
            get
            {
                return _data_cadastro;
            }
            set
            {
                Ondata_cadastroChanging(value);
                ReportPropertyChanging("data_cadastro");
                _data_cadastro = StructuralObject.SetValidValue(value, "data_cadastro");
                ReportPropertyChanged("data_cadastro");
                Ondata_cadastroChanged();
            }
        }
        private Nullable<global::System.DateTime> _data_cadastro;
        partial void Ondata_cadastroChanging(Nullable<global::System.DateTime> value);
        partial void Ondata_cadastroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> data_final
        {
            get
            {
                return _data_final;
            }
            set
            {
                Ondata_finalChanging(value);
                ReportPropertyChanging("data_final");
                _data_final = StructuralObject.SetValidValue(value, "data_final");
                ReportPropertyChanged("data_final");
                Ondata_finalChanged();
            }
        }
        private Nullable<global::System.DateTime> _data_final;
        partial void Ondata_finalChanging(Nullable<global::System.DateTime> value);
        partial void Ondata_finalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 status_id
        {
            get
            {
                return _status_id;
            }
            set
            {
                Onstatus_idChanging(value);
                ReportPropertyChanging("status_id");
                _status_id = StructuralObject.SetValidValue(value, "status_id");
                ReportPropertyChanged("status_id");
                Onstatus_idChanged();
            }
        }
        private global::System.Int32 _status_id;
        partial void Onstatus_idChanging(global::System.Int32 value);
        partial void Onstatus_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 usuario_cadastro_id
        {
            get
            {
                return _usuario_cadastro_id;
            }
            set
            {
                Onusuario_cadastro_idChanging(value);
                ReportPropertyChanging("usuario_cadastro_id");
                _usuario_cadastro_id = StructuralObject.SetValidValue(value, "usuario_cadastro_id");
                ReportPropertyChanged("usuario_cadastro_id");
                Onusuario_cadastro_idChanged();
            }
        }
        private global::System.Int32 _usuario_cadastro_id;
        partial void Onusuario_cadastro_idChanging(global::System.Int32 value);
        partial void Onusuario_cadastro_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 clientes_id
        {
            get
            {
                return _clientes_id;
            }
            set
            {
                Onclientes_idChanging(value);
                ReportPropertyChanging("clientes_id");
                _clientes_id = StructuralObject.SetValidValue(value, "clientes_id");
                ReportPropertyChanged("clientes_id");
                Onclientes_idChanged();
            }
        }
        private global::System.Int32 _clientes_id;
        partial void Onclientes_idChanging(global::System.Int32 value);
        partial void Onclientes_idChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Banco", "fk_solicitacoes_clientes", "tb_clientes")]
        public tb_clientes tb_clientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_clientes>("Banco.fk_solicitacoes_clientes", "tb_clientes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_clientes>("Banco.fk_solicitacoes_clientes", "tb_clientes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_clientes> tb_clientesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_clientes>("Banco.fk_solicitacoes_clientes", "tb_clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_clientes>("Banco.fk_solicitacoes_clientes", "tb_clientes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Banco", "fk_solicitacoes_status", "tb_status")]
        public tb_status tb_status
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_status>("Banco.fk_solicitacoes_status", "tb_status").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_status>("Banco.fk_solicitacoes_status", "tb_status").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_status> tb_statusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_status>("Banco.fk_solicitacoes_status", "tb_status");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_status>("Banco.fk_solicitacoes_status", "tb_status", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Banco", "fk_solicitacoes_usuario_cadastro", "tb_usuarios")]
        public tb_usuarios tb_usuarios1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuarios>("Banco.fk_solicitacoes_usuario_cadastro", "tb_usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuarios>("Banco.fk_solicitacoes_usuario_cadastro", "tb_usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_usuarios> tb_usuarios1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuarios>("Banco.fk_solicitacoes_usuario_cadastro", "tb_usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_usuarios>("Banco.fk_solicitacoes_usuario_cadastro", "tb_usuarios", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Banco", "FK_solicitacoes_tipos", "tb_tipos")]
        public tb_tipos tb_tipos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_tipos>("Banco.FK_solicitacoes_tipos", "tb_tipos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_tipos>("Banco.FK_solicitacoes_tipos", "tb_tipos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_tipos> tb_tiposReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_tipos>("Banco.FK_solicitacoes_tipos", "tb_tipos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_tipos>("Banco.FK_solicitacoes_tipos", "tb_tipos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Banco", "fk_LogSolicitacoes_solicitacoes", "tb_LogSolicitacoes")]
        public EntityCollection<tb_LogSolicitacoes> tb_LogSolicitacoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_LogSolicitacoes>("Banco.fk_LogSolicitacoes_solicitacoes", "tb_LogSolicitacoes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_LogSolicitacoes>("Banco.fk_LogSolicitacoes_solicitacoes", "tb_LogSolicitacoes", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Banco", Name="tb_status")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_status : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_status object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tb_status Createtb_status(global::System.Int32 id)
        {
            tb_status tb_status = new tb_status();
            tb_status.id = id;
            return tb_status;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                OndescricaoChanging(value);
                ReportPropertyChanging("descricao");
                _descricao = StructuralObject.SetValidValue(value, true, "descricao");
                ReportPropertyChanged("descricao");
                OndescricaoChanged();
            }
        }
        private global::System.String _descricao;
        partial void OndescricaoChanging(global::System.String value);
        partial void OndescricaoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Banco", "fk_solicitacoes_status", "tb_solicitacoes")]
        public EntityCollection<tb_solicitacoes> tb_solicitacoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_solicitacoes>("Banco.fk_solicitacoes_status", "tb_solicitacoes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_solicitacoes>("Banco.fk_solicitacoes_status", "tb_solicitacoes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Banco", "FK_LogSolicitacoes_status", "tb_LogSolicitacoes")]
        public EntityCollection<tb_LogSolicitacoes> tb_LogSolicitacoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_LogSolicitacoes>("Banco.FK_LogSolicitacoes_status", "tb_LogSolicitacoes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_LogSolicitacoes>("Banco.FK_LogSolicitacoes_status", "tb_LogSolicitacoes", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Banco", Name="tb_tipos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_tipos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_tipos object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tb_tipos Createtb_tipos(global::System.Int32 id)
        {
            tb_tipos tb_tipos = new tb_tipos();
            tb_tipos.id = id;
            return tb_tipos;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, true, "nome");
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Banco", "FK_solicitacoes_tipos", "tb_solicitacoes")]
        public EntityCollection<tb_solicitacoes> tb_solicitacoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_solicitacoes>("Banco.FK_solicitacoes_tipos", "tb_solicitacoes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_solicitacoes>("Banco.FK_solicitacoes_tipos", "tb_solicitacoes", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Banco", Name="tb_usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_usuarios : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_usuarios object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="status">Initial value of the status property.</param>
        public static tb_usuarios Createtb_usuarios(global::System.Int32 id, global::System.Boolean status)
        {
            tb_usuarios tb_usuarios = new tb_usuarios();
            tb_usuarios.id = id;
            tb_usuarios.status = status;
            return tb_usuarios;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, true, "nome");
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String senha
        {
            get
            {
                return _senha;
            }
            set
            {
                OnsenhaChanging(value);
                ReportPropertyChanging("senha");
                _senha = StructuralObject.SetValidValue(value, true, "senha");
                ReportPropertyChanged("senha");
                OnsenhaChanged();
            }
        }
        private global::System.String _senha;
        partial void OnsenhaChanging(global::System.String value);
        partial void OnsenhaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, "status");
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.Boolean _status;
        partial void OnstatusChanging(global::System.Boolean value);
        partial void OnstatusChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Banco", "fk_solicitacoes_usuario_cadastro", "tb_solicitacoes")]
        public EntityCollection<tb_solicitacoes> tb_solicitacoes1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_solicitacoes>("Banco.fk_solicitacoes_usuario_cadastro", "tb_solicitacoes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_solicitacoes>("Banco.fk_solicitacoes_usuario_cadastro", "tb_solicitacoes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Banco", "fk_LogSolicitacoes_usuarios", "tb_LogSolicitacoes")]
        public EntityCollection<tb_LogSolicitacoes> tb_LogSolicitacoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_LogSolicitacoes>("Banco.fk_LogSolicitacoes_usuarios", "tb_LogSolicitacoes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_LogSolicitacoes>("Banco.fk_LogSolicitacoes_usuarios", "tb_LogSolicitacoes", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
